export const mockAdminMetrics = {
  totalRevenue: "$127,450",
  activeSubscriptions: 342,
  totalUsers: 1247,
  churnRate: "2.4%",
  revenueGrowth: [
    { month: "Jul", revenue: 85000 },
    { month: "Aug", revenue: 92000 },
    { month: "Sep", revenue: 98000 },
    { month: "Oct", revenue: 105000 },
    { month: "Nov", revenue: 115000 },
    { month: "Dec", revenue: 127450 },
  ],
  planDistribution: [
    { plan: "Free", count: 750, color: "#8E8E93" },
    { plan: "Student", count: 245, color: "#007AFF" },
    { plan: "Pro", count: 187, color: "#34C759" },
    { plan: "Elite", count: 65, color: "#FFD700" },
  ],
  revenueByPlan: [
    { plan: "Student", revenue: "$24,500", percentage: 28 },
    { plan: "Pro", revenue: "$74,800", percentage: 59 },
    { plan: "Elite", revenue: "$28,150", percentage: 13 },
  ],
  recentActivity: [
    { type: "signup", user: "Sarah Chen", action: "New signup", time: "2 min ago", icon: "UserPlus", color: "#34C759" },
    { type: "upgrade", user: "Mike Johnson", action: "Upgraded to Pro", time: "15 min ago", icon: "TrendingUp", color: "#007AFF" },
    { type: "ticket", user: "Anna Williams", action: "New support ticket", time: "1 hour ago", icon: "MessageSquare", color: "#FF9500" },
    { type: "signup", user: "David Lee", action: "New signup", time: "2 hours ago", icon: "UserPlus", color: "#34C759" },
    { type: "upgrade", user: "Emma Davis", action: "Upgraded to Elite", time: "3 hours ago", icon: "Crown", color: "#FFD700" },
  ],
};

export const mockUsers = [
  {
    id: "1",
    name: "Sarah Chen",
    email: "sarah.chen@email.com",
    avatar: "SC",
    status: "Active",
    role: "User",
    plan: "Pro",
    billingStatus: "Active",
    nextBilling: "Jan 15, 2025",
    country: "United States",
    usageTime: "47h 32m",
    testsTaken: 156,
    lastActive: "2 hours ago",
    ltv: "$348",
    plansPurchased: 3,
    revenue: "$348",
    joinedDate: "Oct 15, 2024",
    phone: "+1 (555) 123-4567",
  },
  {
    id: "2",
    name: "Mike Johnson",
    email: "mike.j@email.com",
    avatar: "MJ",
    status: "Active",
    role: "User",
    plan: "Elite",
    billingStatus: "Active",
    nextBilling: "Jan 20, 2025",
    country: "United Kingdom",
    usageTime: "89h 15m",
    testsTaken: 243,
    lastActive: "30 min ago",
    ltv: "$876",
    plansPurchased: 5,
    revenue: "$876",
    joinedDate: "Aug 22, 2024",
    phone: "+44 7911 123456",
  },
  {
    id: "3",
    name: "Anna Williams",
    email: "anna.w@email.com",
    avatar: "AW",
    status: "Active",
    role: "User",
    plan: "Student",
    billingStatus: "Active",
    nextBilling: "Jan 10, 2025",
    country: "Canada",
    usageTime: "23h 45m",
    testsTaken: 67,
    lastActive: "5 hours ago",
    ltv: "$120",
    plansPurchased: 2,
    revenue: "$120",
    joinedDate: "Nov 5, 2024",
    phone: "+1 (416) 555-7890",
  },
  {
    id: "4",
    name: "David Lee",
    email: "david.lee@email.com",
    avatar: "DL",
    status: "Suspended",
    role: "User",
    plan: "Free",
    billingStatus: "N/A",
    nextBilling: "N/A",
    country: "Australia",
    usageTime: "12h 20m",
    testsTaken: 34,
    lastActive: "2 days ago",
    ltv: "$0",
    plansPurchased: 0,
    revenue: "$0",
    joinedDate: "Dec 1, 2024",
    phone: "+61 412 345 678",
  },
  {
    id: "5",
    name: "Emma Davis",
    email: "emma.d@email.com",
    avatar: "ED",
    status: "Active",
    role: "Admin",
    plan: "Elite",
    billingStatus: "Active",
    nextBilling: "Jan 25, 2025",
    country: "Singapore",
    usageTime: "156h 40m",
    testsTaken: 412,
    lastActive: "Just now",
    ltv: "$1,540",
    plansPurchased: 8,
    revenue: "$1,540",
    joinedDate: "Jun 10, 2024",
    phone: "+65 9123 4567",
  },
];

export const mockTickets = [
  {
    id: "T-1247",
    user: "Sarah Chen",
    userEmail: "sarah.chen@email.com",
    category: "Billing",
    subject: "Cannot update payment method",
    message: "Hi, I'm trying to update my credit card but the form keeps showing an error. Can you help?",
    status: "Open",
    submittedAt: "2 hours ago",
    priority: "High",
  },
  {
    id: "T-1246",
    user: "Mike Johnson",
    userEmail: "mike.j@email.com",
    category: "Technical",
    subject: "Audio not recording properly",
    message: "The microphone test works but when I start a speaking test, the audio cuts out after 30 seconds.",
    status: "In Progress",
    submittedAt: "5 hours ago",
    priority: "Medium",
  },
  {
    id: "T-1245",
    user: "Anna Williams",
    userEmail: "anna.w@email.com",
    category: "Content",
    subject: "Request for Part 2 topics",
    message: "Could you add more recent IELTS Part 2 topics? I've practiced most of the current ones.",
    status: "Open",
    submittedAt: "1 day ago",
    priority: "Low",
  },
  {
    id: "T-1244",
    user: "Lisa Brown",
    userEmail: "lisa.b@email.com",
    category: "Feedback",
    subject: "Love the new UI update!",
    message: "Just wanted to say the new design is amazing. Much more intuitive than before.",
    status: "Resolved",
    submittedAt: "2 days ago",
    priority: "Low",
  },
  {
    id: "T-1243",
    user: "James Wilson",
    userEmail: "james.w@email.com",
    category: "Billing",
    subject: "Refund request",
    message: "I was charged twice for my subscription. Please refund the duplicate payment.",
    status: "In Progress",
    submittedAt: "3 days ago",
    priority: "High",
  },
];
